export interface ProjectLink {
  url: string;
  icon: string;
  label: string;
}

export interface Project {
  title: string;
  description: string;
  year: string;
  image: string;
  tags: string[];
  links: ProjectLink[];
  showcase?: boolean;
}

export const projects: Project[] = [
  {
    title: "Card Gallery",
    description:
      "An [WIP] interactive card gallery and rules reference app for tabletop card games.",
    year: "2026",
    image: "",
    tags: ["Svelte", "TypeScript", "Tailwind", "DaisyUI"],
    links: [],
    showcase: true,
  },
  {
    title: "StoryGame",
    description:
      "Web application for collaborative story writing where each user continues the story, but can only see the last sentence written by the previous contributor.",
    tags: ["Game", "Svelte", "Tailwind", "Java", "Spring", "Docker"],
    image: "storygame",
    year: "2024",
    links: [
      {
        url: "https://phoenixofforce.dev/StoryGame/",
        icon: "play",
        label: "Play",
      },
      {
        url: "https://github.com/PhoenixofForce/StoryGame",
        icon: "github",
        label: "Source Code",
      },
    ],
    showcase: true,
  },
  {
    title: "SplineCoaster",
    description:
      "Watch cars race on race track that was generated by extruding a spline curve.",
    tags: ["C++", "Mechanic"],
    image: "splineCoasterThumbnail",
    year: "2023",
    links: [
      {
        url: "https://phoenixofforce.dev/SplineCoaster/",
        icon: "globe",
        label: "Watch in Web",
      },
      {
        url: "https://github.com/PhoenixofForce/SplineCoaster",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Speed Barber",
    description:
      "You play as the SpeedBarber who chose the busy travellers of the subway as his customers. Because they are so busy, you have to finish their requests in 10 seconds or less.",
    tags: ["C++", "Game", "GameJam", "Video Demo"],
    image: "speedbarber",
    year: "LD51",
    links: [
      {
        url: "https://ldjam.com/events/ludum-dare/51/speed-barber",
        icon: "globe",
        label: "LD Entry",
      },
      {
        url: "https://github.com/PhoenixofForce/Ludum_Dare_51",
        icon: "github",
        label: "Source Code",
      },
      {
        url: "https://youtu.be/oMbwnkMXZZo",
        icon: "youtube",
        label: "Gameplay Demo",
      },
    ],
    showcase: true,
  },
  {
    title: "Dont Sleep",
    description:
      "A point and click game made in 48h with the current state of my engine. Tomorrow is the next DudumDare and you have to delay the inevitable sleep to see the theme as early as possible.",
    tags: ["Java", "Game", "GameJam", "Video Demo"],
    image: "DontSleep_Cover",
    year: "LD50",
    links: [
      {
        url: "https://ldjam.com/events/ludum-dare/50/dont-sleep",
        icon: "globe",
        label: "LD Entry",
      },
      {
        url: "https://github.com/PhoenixofForce/Ludum_Dare_50",
        icon: "github",
        label: "Source Code",
      },
      {
        url: "https://youtu.be/jSAPulDrY1U",
        icon: "youtube",
        label: "Gameplay Demo",
      },
    ],
  },
  {
    title: "LWJGL Framework",
    description: "A work in progress game codebase written in Java and OpenGL.",
    tags: ["Java", "Game", "Video Demo"],
    image: "engine",
    year: "2022",
    links: [
      {
        url: "https://github.com/PhoenixofForce/LWJGL_Framework",
        icon: "github",
        label: "Source Code",
      },
      {
        url: "https://youtu.be/v2VTF6WdH_E",
        icon: "youtube",
        label: "Gameplay Demo",
      },
    ],
  },
  {
    title: "0 Hour Game",
    description:
      "Turns out 2021 wasnt the last. So i made a game in 0 hours again. This time an easy endless runner where you have to jump over obstacles.",
    tags: ["Java", "GameJam", "Game"],
    image: "zero_game_2",
    year: "0h Jam 2021",
    links: [
      {
        url: "http://0hgame.eu/games.php?year=2021",
        icon: "globe",
        label: "Event Page",
      },
      {
        url: "https://github.com/PhoenixofForce/0HGameJam_21",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Chrono Jump",
    description:
      "A very short game for the 48 LD, which plays with the time. Travel back in time to open doors or change the position of moving platforms.",
    tags: ["Java", "Game", "GameJam"],
    image: "ld48",
    year: "LD48",
    links: [
      {
        url: "https://ldjam.com/events/ludum-dare/48/chronojump",
        icon: "globe",
        label: "LD Entry",
      },
      {
        url: "https://github.com/PhoenixofForce/Ludum_Dare_48",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "DnD Utils",
    description:
      "Want to roll some digital dice? Compare Spell damage? Then this site is for you.",
    tags: ["DND", "Svelte", "Web", "Tool"],
    image: "dnd_util",
    year: "2021",
    links: [
      {
        url: "https://phoenixofforce.github.io/DND_Utils/",
        icon: "globe",
        label: "Website",
      },
      {
        url: "https://github.com/PhoenixofForce/DND_Utils",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Dungeon Creator",
    description: "Create a custom Dungeon for your next session.",
    tags: ["DND", "Svelte", "Web", "Tool"],
    image: "dungeon_creator",
    year: "2020",
    links: [
      {
        url: "https://phoenixofforce.github.io/DungeonCreator/",
        icon: "globe",
        label: "Website",
      },
      {
        url: "https://github.com/PhoenixofForce/DungeonCreator",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Dungeon Viewer",
    description:
      "Host a game, share the link and watch your player struggle as you throw some dragons at them! This project no longer works as the host service I used discontinued its free plan.",
    tags: ["DND", "Svelte", "Web", "Tool"],
    image: "dungeon_viewer_1",
    year: "2020",
    links: [
      {
        url: "https://phoenixofforce.github.io/Dungeon_Viewer/",
        icon: "globe",
        label: "Website",
      },
      {
        url: "https://github.com/PhoenixofForce/Dungeon_Viewer",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Entity Component System",
    description:
      "This is a test of an entity component system (ecs) featuring abilities, a moving platform, an enemy and a dash.",
    tags: ["Java", "Mechanic", "Game", "Video Demo"],
    image: "ecs",
    year: "2020",
    links: [
      {
        url: "https://github.com/PhoenixofForce/ECS_Test",
        icon: "github",
        label: "Source Code",
      },
      {
        url: "https://youtu.be/3pnSehOTXQk",
        icon: "youtube",
        label: "Gameplay Demo",
      },
    ],
  },
  {
    title: "0 Hour Game",
    description:
      "A Game made in 0 Hours, -40 Minutes. This game jam was (supposed to be) the last of its kind. Play my version of Space Invaders",
    tags: ["Java", "GameJam", "Game"],
    image: "zero_game",
    year: "0h Jam 2020",
    links: [
      {
        url: "http://0hgame.eu/games.php?year=2020",
        icon: "globe",
        label: "Event Page",
      },
      {
        url: "https://github.com/PhoenixofForce/0HGameJam",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "LaTxT",
    description: "Write LaTxT-like code to create magnificent .txt files.",
    tags: ["Java", "Tool"],
    image: "",
    year: "2020",
    links: [
      {
        url: "https://github.com/PhoenixofForce/LaTxT",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Parser",
    description:
      "A parser for all sort of languages. Write your own language and compile the code in Java.",
    tags: ["Java"],
    image: "",
    year: "2020",
    links: [
      {
        url: "https://github.com/PhoenixofForce/Parser",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Bloody Medic",
    description:
      "Dwelve into the Dungeon to rescue your villagers. But watch your health as your life is currency.",
    tags: ["GameJam", "Game", "Java"],
    image: "bloody_medic",
    year: "LD44",
    links: [
      {
        url: "https://ldjam.com/events/ludum-dare/44/bloody-medic",
        icon: "globe",
        label: "LD Entry",
      },
      {
        url: "https://github.com/Nottrex/LudumDare44",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Dialogue System",
    description:
      "Dialogue System in the command line that uses tags, which are established in other projects of mine.",
    tags: ["Mechanic", "Java"],
    image: "",
    year: "2019",
    links: [
      {
        url: "https://github.com/PhoenixofForce/DialogueSystem",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "RayCast Scene",
    description:
      "This raycast scene renders 3D Prisms (objects with flat top and bottom) by sending rays from the player position in all directions.",
    tags: ["Mechanic", "Java", "Video Demo"],
    image: "raycast",
    year: "2018",
    links: [
      {
        url: "https://github.com/PhoenixofForce/RayCast-Scene",
        icon: "github",
        label: "Source Code",
      },
      {
        url: "https://youtu.be/uu5uI9NeAL0",
        icon: "youtube",
        label: "Gameplay Demo",
      },
    ],
  },
  {
    title: "Triangulated Polygon Collision",
    description:
      "You can create polygons that get translated into a group of triangles. These triangles are used for collision testing with the Separating Axis Theorem.",
    tags: ["Mechanic", "Java", "Video Demo"],
    image: "axis",
    year: "2018",
    links: [
      {
        url: "https://github.com/PhoenixofForce/TriangulatedPolygonCollision",
        icon: "github",
        label: "Source Code",
      },
      {
        url: "https://youtu.be/fTwLpqHtpE8",
        icon: "youtube",
        label: "Gameplay Demo",
      },
    ],
  },
  {
    title: "Clicker Defense",
    description:
      "Protect your Base from very unfriendly Slimes. Get resources to build powerful Towers.",
    tags: ["GameJam", "Game", "Java"],
    image: "clicker_defense",
    year: "LD41",
    links: [
      {
        url: "https://ldjam.com/events/ludum-dare/41/clickerdefense",
        icon: "globe",
        label: "LD Entry",
      },
      {
        url: "https://github.com/PhoenixofForce/LudumDare41",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Texture Packer",
    description: "A texture packer based on steering algorithms.",
    tags: ["Java", "Tool", "Video Demo"],
    image: "texture_packer",
    year: "2017",
    links: [
      {
        url: "https://github.com/PhoenixofForce/TexturePacker",
        icon: "github",
        label: "Source Code",
      },
      {
        url: "https://youtu.be/nJZJ_yAq94o",
        icon: "youtube",
        label: "Gameplay Demo",
      },
    ],
  },
  {
    title: "LevelEditor",
    description:
      "Import your spritesheet and start making levels for your game.",
    tags: ["Java", "Tool", "Video Demo"],
    image: "level_editor",
    year: "2017",
    links: [
      {
        url: "https://github.com/PhoenixofForce/Level_Editor",
        icon: "github",
        label: "Source Code",
      },
      {
        url: "https://youtu.be/mzzermlVRTw",
        icon: "youtube",
        label: "Gameplay Demo",
      },
    ],
    showcase: true,
  },
  {
    title: "Jump and Run",
    description:
      "Jump your way through multiple levels to collect all shiny coins.",
    tags: ["Game", "Java"],
    image: "jump_and_run",
    year: "2017",
    links: [
      {
        url: "https://github.com/Nottrex/JumpAndRun",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Tank My Bug",
    description:
      "In this buggy Shooter you can shoot your friends on the couch next to you.",
    tags: ["GameJam", "Game", "Java"],
    image: "tank_my_bug",
    year: "Kenney 1",
    links: [
      {
        url: "https://phoenixofforce.itch.io/tankmybug",
        icon: "globe",
        label: "Event Page",
      },
      {
        url: "https://github.com/PhoenixofForce/Kenney_Jam_1",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Lights Out",
    description:
      "An earthquake caused your lights to turn off. Find a way out of the building as long as you can!",
    tags: ["GameJam", "Game", "Java"],
    image: "Lights_Out",
    year: "LD39",
    links: [
      {
        url: "https://ldjam.com/events/ludum-dare/39/lightsout",
        icon: "globe",
        label: "LD Entry",
      },
      {
        url: "https://github.com/PhoenixofForce/Ludum_Dare_39",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "My Lamp",
    description:
      "Jump across one screen full of enemies while you juggle your lamps fuel.",
    tags: ["GameJam", "Game", "Java"],
    image: "my_lamp",
    year: "GMTK 1",
    links: [
      {
        url: "https://phoenixofforce.itch.io/my-lamp",
        icon: "globe",
        label: "Event Page",
      },
      {
        url: "https://github.com/PhoenixofForce/GMTK_Jam",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
  {
    title: "Hex Game",
    description: "Blast of your enemies in this turn based stategy game.",
    tags: ["Game", "Java"],
    image: "hexgame_",
    year: "2017",
    links: [
      {
        url: "https://github.com/Nottrex/HexGame_",
        icon: "github",
        label: "Source Code",
      },
    ],
  },
];
